# CATS project group 14

In [64]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn import linear_model
from sklearn import decomposition
from matplotlib import pyplot

In [13]:
train_call_original = pd.read_csv("./data/Train_call.txt", sep='\t')
train_clinical_original = pd.read_csv("./data/Train_clinical.txt", sep='\t')

# Look into the data

In [14]:
train_clinical_original.head()

      Sample    Subgroup
0  Array.129       HER2+
1   Array.34         HR+
2   Array.67         HR+
3   Array.24  Triple Neg
4   Array.22  Triple Neg

In [15]:
train_clinical_original.shape

(100, 2)

In [16]:
train_call_original.head()

,Chromosome,Start,End,Nclone,Array.129,Array.34,Array.67,Array.24,Array.22,Array.36,...,Array.64,Array.89,Array.30,Array.35,Array.93,Array.10,Array.123,Array.100,Array.134,Array.130
0,1,2927,43870,3,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
1,1,85022,216735,4,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
2,1,370546,372295,4,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,-1,0
3,1,471671,786483,5,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,-1,0
4,1,792533,907406,13,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,-1,0

In [17]:
train_call_original.shape

(2834, 104)

In [18]:
train_clinical_original['Subgroup'].value_counts()

HR+           36
HER2+         32
Triple Neg    32
Name: Subgroup, dtype: int64

# Data processing from Dora - not needed
1. Format train_call: from 4 feature columns, make one and transpose table

In [20]:
# make new table for processing
train_call = train_call_original
#make new column from 4 feature columns
feature_cols = ['Chromosome', 'Start', 'End', 'Nclone']
train_call['Feature'] = train_call[feature_cols].astype(str).agg('-'.join, axis=1)
#drop old features
train_call = train_call.drop(feature_cols, axis=1)
#2. transpose df
train_call = train_call.set_index('Feature').transpose()
train_call.head()

Feature,1-2927-43870-3,1-85022-216735-4,1-370546-372295-4,1-471671-786483-5,1-792533-907406-13,1-912799-1266212-96,1-1271190-1590570-45,1-1676445-1703748-4,1-1738295-2477597-104,1-2481927-2562342-14,...,23-151067607-152416606-159,23-152422390-152548587-20,23-152552851-152570071-6,23-152576854-152935130-64,23-152994680-153054487-5,23-153062077-153452633-57,23-153466463-153491568-4,23-153504394-153933426-55,23-153938998-153989329-5,23-153997146-154492924-43
Array.129,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,0,1,1,1,1,1
Array.34,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.67,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.24,0,0,0,0,0,0,0,-1,0,0,...,0,0,0,0,0,0,0,0,0,0
Array.22,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

In [21]:
train_call.shape

(100, 2834)

In [41]:
train_call = train_call+1

In [42]:
#minimum value
min(train_call.min())

0

In [43]:
#max value
max(train_call.max())

3

# Repeated double loop CV function

The above data processing steps are not needed, here the data processing from Niels was used.

In [7]:
# Data processing

data = pd.read_csv("./data/train_call.txt", index_col=0, delimiter="\t").transpose()
topInfo = data.iloc[:3]
data = data.iloc[4:].dropna(axis=1)
data
classes = pd.read_csv("./data/train_clinical.txt", delimiter="\t", index_col=0)
classes
data = classes.join(data).set_index("Subgroup").dropna()
# Add 1 to data because of chi-square feature selection
data = data+1
# look into
data.iloc[0:5, 0:5]

              1    1    1    1    1
Subgroup
HR+         1.0  1.0  1.0  1.0  1.0
HR+         1.0  1.0  1.0  1.0  1.0
Triple Neg  1.0  1.0  1.0  1.0  1.0
Triple Neg  1.0  1.0  1.0  1.0  1.0
HR+         1.0  1.0  1.0  1.0  1.0

Here I am trying to make eval function, this is not ready yet.

In [54]:
from sklearn.metrics import confusion_matrix
from scikitplot.metrics import plot_precision_recall
 
       
    
def evaluate(best_model, test_data):
    print("Best estimator:", best_estimator)
    print('Model Performance', end='\n')
    print('1. Confusion matrix. i-th row: true label i-th class. j-th column: predicted label, j-th class', end='\n')
    CM = confusion_matrix(test_data.index, predictions)
    print(CM)
    T_00 = CM[0][0]
    F_01 = CM[0][1]
    F_02 = CM[0][2]
    F_10 = CM[1][0] 
    T_11 = CM[1][1]
    F_12 = CM[1][2]
    F_20 = CM[2][0]
    F_21 = CM[2][1]
    T_22 = CM[2][2]
    All = np.sum(CM)
    accuracy = round((T_00+T_11+T_22)/All)
    return accuracy


# put this into evaluate function
def evaluate_notyet(model, data):
    #print(Confusion matrix. i-th row: true label i-th class. j-th column: predicted label, j-th class', end='\n')
    #confusion_matrix = confusion_matrix(test_labels, predictions)
    accuracy = accuracy_score(inner_test_data.index, lr.predict(inner_test_data))
    cm = confusion_matrix(inner_test_data.index, model.predict(data), labels=model.classes_)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=y)
    disp.plot()

Double CV function customized from: https://machinelearningmastery.com/how-to-fix-futurewarning-messages-in-scikit-learn/

In [74]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, cross_val_score, StratifiedKFold
import sklearn.feature_selection as feature_selection
from sklearn.metrics import accuracy_score

def repeated_nested_cv(model): 
    global num_repeats, outer_repeats, inner_repeats, data, chi_num_features, search
    for i in range(num_repeats):
        repeat_results = list()
        cv_outer = StratifiedKFold(n_splits=outer_repeats, shuffle=True) # check if we have to shuffle    
        outer_results = list()
        for train_index, test_index in cv_outer.split(data, data.index):
            #outer loop
            train_data = data.iloc[train_index]
            test_data = data.iloc[test_index]
            # fit Chi-square feature selection model to determine best features 
            best_features = feature_selection.SelectKBest(feature_selection.chi2, k=chi_num_features).fit(train_data, train_data.index)
            # re-assign inner data to only best features
            train_data = train_data.transpose().loc[best_features.get_support()].transpose()
            test_data = test_data.transpose().loc[best_features.get_support()].transpose()
            # define inner CV - should this be here?
            cv_inner = StratifiedKFold(n_splits=inner_repeats, shuffle=True) # this could be moved up?
            # define hyperparameter search in the inner loop. The inner loop is defined by cv = cv_inner. If there were no loops,
            # cv argument would be just a number, but here it is an iterable.
            # final model is refit on the entire train set with the best hyperparams found during the search
            search = search_method(model, space, scoring='accuracy', cv=cv_inner, refit=True) 
            result = search.fit(train_data, train_data.index)
            # get the best performing model fit on the whole training set
            best_model = result.best_estimator_
            print('best_model in outer loop fold:', best_model)
            # use model on the outer loop test set
            yhat = best_model.predict(test_data)
            # evaluate the model
            acc = accuracy_score(test_data.index, yhat, normalize = True)
            # store the result
            outer_results.append(acc)
        repeat_results.append(outer_results)
        print('Accuracies from all outer folds:', repeat_results)
    print('Mean accuracy and (std) from the repeats: %.3f (%.3f)' % (np.mean(repeat_results), np.std(repeat_results)))


def repeated_nested_cv_with_eval(model): 
    global num_repeats, outer_repeats, inner_repeats, data, chi_num_features, search
    for i in range(num_repeats):
        repeat_results = list()
        cv_outer = StratifiedKFold(n_splits=outer_repeats, shuffle=True) # check if we have to shuffle    
        outer_results = list()
        for train_index, test_index in cv_outer.split(data, data.index):
            #outer loop
            train_data = data.iloc[train_index]
            test_data = data.iloc[test_index]
            # fit Chi-square feature selection model to determine best features 
            best_features = feature_selection.SelectKBest(feature_selection.chi2, k=chi_num_features).fit(train_data, train_data.index)
            # re-assign inner data to only best features
            train_data = train_data.transpose().loc[best_features.get_support()].transpose()
            test_data = test_data.transpose().loc[best_features.get_support()].transpose()
            # define inner CV - should this be here?
            cv_inner = StratifiedKFold(n_splits=inner_repeats, shuffle=True) # this could be moved up?
            # define hyperparameter search in the inner loop. The inner loop is defined by cv = cv_inner. If there were no loops,
            # cv argument would be just a number, but here it is an iterable.
            # final model is refit on the entire train set with the best hyperparams found during the search
            search = search_method(model, space, scoring='accuracy', cv=cv_inner, refit=True) 
            cv_result = search.fit(train_data, train_data.index)
            # get the best performing model fit on the whole training set
            best_model = cv_result.best_estimator_
            print('best_model in outer loop fold:', best_model)
            # use model on the outer loop test set
            predictions = best_model.predict(test_data)
            # evaluate
            result = evaluate(best_model, test_data)
            # store the result
            outer_results.append(result)
        repeat_results.append(outer_results)
        print(repeat_results)
    print('Mean accuracy and (std) from the repeats: %.3f (%.3f)' % (np.mean(repeat_results), np.std(repeat_results)))

In [75]:
from sklearn.linear_model import LogisticRegression

# specify classifier model
lr_model = linear_model.LogisticRegression(penalty="l2", max_iter=10000, multi_class = 'ovr', solver = 'liblinear')

# specify parameter search space and search method
space = dict()
space['C'] = [100, 10, 1.0, 0.1, 0.01]
search_method = GridSearchCV # or RandomizedSearchCV

# parameters of repeated nested CV
num_repeats = 2 # outer-outer repeats
outer_repeats = 2
inner_repeats = 2
chi_num_features = 20

repeated_nested_cv(lr_model)

best_model in outer loop fold: LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
best_model in outer loop fold: LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
Accuracies from all outer folds: [[0.56, 0.7346938775510204]]
best_model in outer loop fold: LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
best_model in outer loop fold: LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)
Accuracies from all outer folds: [[0.62, 0.6326530612244898]]
Mean accuracy and (std) from the repeats: 0.626 (0.006)

C:\Programok\Anaconda\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Programok\Anaconda\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

In [ ]:
# I didn't finish this bc I used the above


def nested_cv_according_to_Nils(outer_repeats, inner_repeats, data, chi_num_features, model, search_method):
    global outer_repeats, inner_repeats, data, chi_num_features, model, search_method
    cv_outer = StratifiedKFold(n_splits=outer_repeats, shuffle=True, random_state=1) # check if we have to shuffle
    cv_inner = StratifiedKFold(n_splits=inner_repeats, shuffle=True, random_state=1)
    outer_results = list()
    for train_index, test_index in cv_outer.split(data, data.index):
        #outer loop
        train_data = data.iloc[train_index]
        test_data = data.iloc[test_index]
        for inner_train_index, inner_test_index in cv_inner.split(train_data, train_data.index):
            #print(inner_test_index.tolist(), test_index.tolist())
            inner_train_data = train_data.iloc[inner_train_index]
            inner_test_data = train_data.iloc[inner_test_index]
            # fit Chi-square feature selection model to determine best features 
            best_features = feature_selection.SelectKBest(feature_selection.chi2, k=chi_num_features).fit(inner_train_data, inner_train_data.index)
            # re-assign inner data to only best features
            inner_train_data = inner_train_data.transpose().loc[best_features.get_support()].transpose()
            inner_test_data = inner_test_data.transpose().loc[best_features.get_support()].transpose()
            # define hyperparameter search in the inner loop
            # final model is refit on the entire train set with the best hyperparams found during the search
            search = search_method(model, space, scoring='accuracy', cv=cv_inner, refit=True) 
            result = search.fit(X_train, y_train)
            
            model.fit(inner_train_data, inner_train_data.index)
            evaluate_inner(model, inner_test_data)